# Generated by Django 5.0.7 on 2024-07-25 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
    ]
