# Generated by Django 5.0.7 on 2024-07-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='image',
            field=models.ImageField(upload_to='workouts'),
        ),
    ]
